### ISSUE TITLE
Creation of new Monitors for UR

### ISSUE THREAD

**Issue by captiglo** [tronyx/tronitor#58]
Creation of new Monitors in UR does not work.
The reason for this is a wrongly defined Content Type in the curl POST operation for UR, so the JSON file is not processed correctly by UR:

Content-Type: application/x-www-form-urlencoded

To fix this issue, remove from line 1328 und 1330 in tronitor.sh the reference to this wrong Content-Type mentioned above.

btw: It would be great to create new Monitors without using a template file. Consider this as a feature request ;-)

**Comment by tronyx** [comment]
Sorry for the delay in response. I was not notified via e-mail of this issue. I will get the issue fixed ASAP. If you have any ideas for how to implement creation of monitors without the template file, please let me know. I'm not putting nearly as much time into this as I used to as the main purpose is to be able to have your own maintenance windows with pausing tests more than the ability to create new monitors, etc.

**Comment by tronyx** [comment]
Please test with latest develop branch script.

**Comment by tronyx** [comment]
Merged the fix. If you have suggestions, please open a PR. Closing this.
