### ISSUE TITLE
Uptimerobot API limit

### ISSUE THREAD

**Issue by Flip76** [tronyx/tronitor#60]
**Is your feature request related to a problem? Please describe.**
I am running 5 monitors but as Uptimerobot introduced a API rate limit (10 per minute for the free edition) I run into the message "There seems to be an issue connecting to Uptimerobot. Please try again in a few minutes." every second run. So I did a trace and I saw that even a pause/unpause for 1 specific monitor will iterate (curl) through all monitors. 

**Describe the solution you'd like**
Would it be possible to reduce the number of api (curl-) calls? Especially when only working with single monitor-id's?

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by tronyx** [comment]
It was written to grab everything initially so it could easily list them all and their status. It would take too long for me to rewrite the entire script to work with only the specified monitors when a pause or unpause is requested. Time that I, unfortunately, do not have right now and will not have in the foreseeable future. I will welcome PRs, code snippets, etc, but that's all I can do.

With UptimeRobots introduction of the API limits, I personally switched over to using a self-hosted instance of HealthChecks.io and Upptime (works through GitHub) to monitor my externally facing Services.

**Comment by Flip76** [comment]
Unfortunately I am a rookie with git but I think, changing only 1 line would to the trick (at least for UptimeRobot):

# replacing line 767

`curl --fail -s -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" "${apiUrl}"getMonitors -d "api_key=${apiKey}" -d "format=json" -d "monitors=${monitor}" > "${tempDir}${monitor}".txt || fatal`

with

`jq -r '. | {stat: .stat, pagination: .pagination, monitors: [.monitors[] | select(.id=='"${monitor}"')]} | .pagination.total=1' ${monitorsFullFile} > "${tempDir}${monitor}".txt || fatal`

**Comment by tronyx** [comment]
Your solution does work, which is awesome, so thank you. Just some minor things I have to change/remove so I'm going to close your PR and commit the change to the develop branch for you to test. I did test it a bit myself and it seems to be working. Bravo.

**Comment by Flip76** [comment]
Glad I could help a little bit! And finally a good reason to play around with git (which was on my to-do list for a long time) :-)
Sorry for the comments in the code but the contribution guidelines stated it, so I added them. Will checkout the develop branch and give it a try.

**Comment by tronyx** [comment]
No worries, comments are always helpful. Glad you got the bump to play with git. Let me know how your testing goes and, if all is well, I will merge things into the master branch.

**Comment by Flip76** [comment]
I just tested the develop branch and it works great - i tried:

- list
- pause/unpause single monitor
- pause/unpause multiple monitors (comma seperated)
- pause/unpause all monitors

Of course this doesn't solve the problem that you only have 10 api calls per minute but instead you can have up to 50 monitors in the free plan. So if you have more than 10 monitors in the free plan and you want to pause/unpause them all, you will always run into the api call restriction and therefore in an error. 

But I passed this question directly to uptime robot if they can:

a) implement a id-all argument
b) implement multiple ids in one call
c) giving another solution if a) and b) doesn't work

Let's see what they respond :-)

**Comment by tronyx** [comment]
Awesome, thanks so much for testing and getting back to me. I hope they respond and can make some improvements, but I'm not holding me breath. Keep me posted.

If you think this can be closed, go ahead and close it and I will merge the develop branch into master.

**Comment by Flip76** [comment]
I will let you know as soon as they come back with an answer. However I will definitely have a look into a self-hosted instance of HealthChecks.io and Upptime. Thanks for that and for the quick merge!
